# Generated by Django 6.1.1 on 2026-09-07 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('COMPLETED', 'Completed')], db_index=True, default='DRAFT', max_length=20)),
                ('team_a_score', models.PositiveIntegerField(blank=True, null=True)),
                ('team_b_score', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('player_of_the_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='potm_matches', to='players.player')),
            ],
            options={
                'verbose_name_plural': 'matches',
                'ordering': ['-match_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MatchParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='players.player')),
            ],
        ),
        migrations.CreateModel(
            name='MatchTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('A', 'Team A'), ('B', 'Team B')], max_length=1)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='matches.match')),
            ],
        ),
        migrations.CreateModel(
            name='GoalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='1-based goal order within the match')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assister', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assists_made', to='players.player')),
                ('scorer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals_scored', to='players.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='matches.match')),
                ('scoring_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals_scored', to='matches.matchteam')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MatchTeamPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_assignments', to='players.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster', to='matches.matchteam')),
            ],
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('team_a_score__isnull', True), ('team_a_score__gte', 0), _connector='OR'), name='match_team_a_score_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('team_b_score__isnull', True), ('team_b_score__gte', 0), _connector='OR'), name='match_team_b_score_non_negative'),
        ),
        migrations.AddIndex(
            model_name='matchparticipant',
            index=models.Index(fields=['match', 'player'], name='matches_mat_match_i_4c938e_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchparticipant',
            constraint=models.UniqueConstraint(fields=('match', 'player'), name='unique_match_participant'),
        ),
        migrations.AddConstraint(
            model_name='matchteam',
            constraint=models.UniqueConstraint(fields=('match', 'side'), name='unique_match_team_side'),
        ),
        migrations.AddIndex(
            model_name='goalevent',
            index=models.Index(fields=['match', 'scorer'], name='matches_goa_match_i_ed22fd_idx'),
        ),
        migrations.AddIndex(
            model_name='goalevent',
            index=models.Index(fields=['match', 'assister'], name='matches_goa_match_i_8fb44f_idx'),
        ),
        migrations.AddConstraint(
            model_name='goalevent',
            constraint=models.UniqueConstraint(fields=('match', 'order'), name='unique_goal_order_per_match'),
        ),
        migrations.AddIndex(
            model_name='matchteamplayer',
            index=models.Index(fields=['team', 'player'], name='matches_mat_team_id_51d481_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchteamplayer',
            constraint=models.UniqueConstraint(fields=('team', 'player'), name='unique_team_player'),
        ),
    ]
