# Generated by Django 6.1.1 on 2026-09-07 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable')], db_index=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_availabilities', to='players.player')),
            ],
            options={
                'verbose_name_plural': 'match availabilities',
                'indexes': [models.Index(fields=['match', 'status'], name='matches_mat_match_i_eb0ed5_idx')],
                'constraints': [models.UniqueConstraint(fields=('match', 'player'), name='unique_match_availability')],
            },
        ),
    ]
