# Generated by Django 6.1.1 on 2026-09-07 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_matchavailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='player_of_the_match',
        ),
    ]
