# Generated by Django 6.1.1 on 2026-09-08 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_remove_match_player_of_the_match'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='matchteam',
            name='unique_match_team_side',
        ),
        migrations.RemoveField(
            model_name='goalevent',
            name='scoring_team',
        ),
        migrations.RemoveIndex(
            model_name='matchteamplayer',
            name='matches_mat_team_id_51d481_idx',
        ),
        migrations.RemoveConstraint(
            model_name='matchteamplayer',
            name='unique_team_player',
        ),
        migrations.RemoveConstraint(
            model_name='match',
            name='match_team_a_score_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='match',
            name='match_team_b_score_non_negative',
        ),
        migrations.RemoveField(
            model_name='matchteamplayer',
            name='player',
        ),
        migrations.RemoveField(
            model_name='matchteamplayer',
            name='team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_a_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_b_score',
        ),
        migrations.DeleteModel(
            name='MatchTeam',
        ),
        migrations.DeleteModel(
            name='MatchTeamPlayer',
        ),
    ]
