# Generated by Django 6.1.1 on 2026-09-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_remove_matchteam_unique_match_team_side_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team_a_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchparticipant',
            name='side',
            field=models.CharField(blank=True, choices=[('A', 'Team A'), ('B', 'Team B')], max_length=1, null=True),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('team_a_score__isnull', True), ('team_a_score__gte', 0), _connector='OR'), name='match_team_a_score_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('team_b_score__isnull', True), ('team_b_score__gte', 0), _connector='OR'), name='match_team_b_score_non_negative'),
        ),
    ]
