# Generated by Django 6.1.1 on 2026-09-15 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_match_team_a_score_match_team_b_score_and_more'),
        ('players', '0002_player_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed')], db_index=True, default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-week_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='game_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='matches.gameweek'),
        ),
        migrations.CreateModel(
            name='GameWeekTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='matches.gameweek')),
                ('players', models.ManyToManyField(blank=True, related_name='game_week_teams', to='players.player')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(blank=True, help_text='Which named game-week team played as Side A in this fixture (display/prefill only).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixtures_as_a', to='matches.gameweekteam'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixtures_as_b', to='matches.gameweekteam'),
        ),
        migrations.AddConstraint(
            model_name='gameweekteam',
            constraint=models.UniqueConstraint(fields=('game_week', 'name'), name='unique_game_week_team_name'),
        ),
    ]
