# Generated by Django 6.1.1 on 2026-09-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, choices=[('DEFENDER', 'Defender'), ('MIDFIELDER', 'Midfielder'), ('STRIKER', 'Striker')], help_text='Required for new registrations; existing players may not have one set yet.', max_length=20, null=True),
        ),
    ]
