# Generated by Django 6.1.1 on 2026-09-07 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_type', models.CharField(choices=[('POTW', 'Player of the Week'), ('TOTW', 'Team of the Week'), ('POTM_MONTH', 'Player of the Month'), ('GOLDEN_BOOT', 'Golden Boot'), ('TOP_ASSISTER', 'Top Assister'), ('MOST_POTW', 'Most Player of the Week Awards'), ('MOST_POTM', 'Most Player of the Match Awards')], db_index=True, max_length=32)),
                ('year', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('month', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False, help_text='Admin confirmation for recommended weekly awards.')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(blank=True, help_text='Set for weekly awards tied to a Monday match.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='matches.match')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AwardRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='awards.award')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards_received', to='players.player')),
            ],
            options={
                'ordering': ['rank', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='award',
            index=models.Index(fields=['award_type', 'year', 'month'], name='awards_awar_award_t_d42c56_idx'),
        ),
        migrations.AddIndex(
            model_name='award',
            index=models.Index(fields=['award_type', 'match'], name='awards_awar_award_t_fc5a66_idx'),
        ),
        migrations.AddConstraint(
            model_name='award',
            constraint=models.UniqueConstraint(condition=models.Q(('match__isnull', False)), fields=('award_type', 'match'), name='unique_weekly_award_per_match_type'),
        ),
        migrations.AddConstraint(
            model_name='award',
            constraint=models.UniqueConstraint(condition=models.Q(('month__isnull', False), ('year__isnull', False)), fields=('award_type', 'year', 'month'), name='unique_monthly_award_per_period_type'),
        ),
        migrations.AddConstraint(
            model_name='award',
            constraint=models.CheckConstraint(condition=models.Q(('month__isnull', True), models.Q(('month__gte', 1), ('month__lte', 12)), _connector='OR'), name='award_month_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='awardrecipient',
            constraint=models.UniqueConstraint(fields=('award', 'player'), name='unique_award_recipient'),
        ),
    ]
