# Generated by Django 6.1.1 on 2026-09-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='award',
            name='unique_monthly_award_per_period_type',
        ),
        migrations.AddConstraint(
            model_name='award',
            constraint=models.UniqueConstraint(condition=models.Q(('match__isnull', True), ('month__isnull', False), ('year__isnull', False)), fields=('award_type', 'year', 'month'), name='unique_monthly_award_per_period_type'),
        ),
    ]
