# Generated by Django 6.1.1 on 2026-09-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_remove_award_unique_monthly_award_per_period_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='award_type',
            field=models.CharField(choices=[('POTW', 'Player of the Week'), ('TOTW', 'Team of the Week'), ('POTM_MONTH', 'Player of the Month'), ('GOLDEN_BOOT', 'Golden Boot'), ('TOP_ASSISTER', 'Top Assister'), ('MOST_POTW', 'Most Player of the Week Awards')], db_index=True, max_length=32),
        ),
    ]
