# Generated by Django 6.1.1 on 2026-09-15 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_alter_award_award_type'),
        ('matches', '0006_gameweek_match_game_week_gameweekteam_match_team_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='game_week',
            field=models.ForeignKey(blank=True, help_text='Set for weekly awards aggregated across a multi-fixture game week.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='matches.gameweek'),
        ),
        migrations.AlterField(
            model_name='award',
            name='match',
            field=models.ForeignKey(blank=True, help_text='Set for weekly awards tied to a standalone Monday match.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='matches.match'),
        ),
        migrations.AddIndex(
            model_name='award',
            index=models.Index(fields=['award_type', 'game_week'], name='awards_awar_award_t_82dc73_idx'),
        ),
        migrations.AddConstraint(
            model_name='award',
            constraint=models.UniqueConstraint(condition=models.Q(('game_week__isnull', False)), fields=('award_type', 'game_week'), name='unique_weekly_award_per_game_week_type'),
        ),
    ]
